In [49]:
import pandas as pd
df = pd.read_csv("C:\\Users\\HP\\Downloads\\train.csv")

In [50]:
df

ID  Gender Ever_Married  Age Graduated     Profession  \
0     462809    Male           No   22        No     Healthcare   
1     462643  Female          Yes   38       Yes       Engineer   
2     466315  Female          Yes   67       Yes       Engineer   
3     461735    Male          Yes   67       Yes         Lawyer   
4     462669  Female          Yes   40       Yes  Entertainment   
...      ...     ...          ...  ...       ...            ...   
8063  464018    Male           No   22        No            NaN   
8064  464685    Male           No   35        No      Executive   
8065  465406  Female           No   33       Yes     Healthcare   
8066  467299  Female           No   27       Yes     Healthcare   
8067  461879    Male          Yes   37       Yes      Executive   

      Work_Experience Spending_Score  Family_Size  Var_1 Segmentation  
0                 1.0            Low          4.0  Cat_4            D  
1                 NaN        Average          3.0  Cat_4            A  
2                 1.0            Low          1.0  Cat_6            B  
3                 0.0           High          2.0  Cat_6            B  
4                 NaN           High          6.0  Cat_6            A  
...               ...            ...          ...    ...          ...  
8063              0.0            Low          7.0  Cat_1            D  
8064              3.0            Low          4.0  Cat_4            D  
8065              1.0            Low          1.0  Cat_6            D  
8066              1.0            Low          4.0  Cat_6            B  
8067              0.0        Average          3.0  Cat_4            B  

[8068 rows x 11 columns]

In [51]:
df.drop("ID",axis=1,inplace=True)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Gender           8068 non-null   object 
 1   Ever_Married     7928 non-null   object 
 2   Age              8068 non-null   int64  
 3   Graduated        7990 non-null   object 
 4   Profession       7944 non-null   object 
 5   Work_Experience  7239 non-null   float64
 6   Spending_Score   8068 non-null   object 
 7   Family_Size      7733 non-null   float64
 8   Var_1            7992 non-null   object 
 9   Segmentation     8068 non-null   object 
dtypes: float64(2), int64(1), object(7)
memory usage: 630.4+ KB


In [53]:
df.describe()

Age  Work_Experience  Family_Size
count  8068.000000      7239.000000  7733.000000
mean     43.466906         2.641663     2.850123
std      16.711696         3.406763     1.531413
min      18.000000         0.000000     1.000000
25%      30.000000         0.000000     2.000000
50%      40.000000         1.000000     3.000000
75%      53.000000         4.000000     4.000000
max      89.000000        14.000000     9.000000

In [66]:
df["Segmentation"].unique()

array(['D', 'A', 'B', 'C'], dtype=object)

In [55]:
float_pipeline = []
object_pipeline = []
index = 0
for _types in df.dtypes:
    if _types == "object":
        object_pipeline.append(df.columns[index])
        pass
    else:
        float_pipeline.append(df.columns[index])
        pass
    index = index + 1
    pass

In [56]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

num_pipline = Pipeline([
    ('imputer',SimpleImputer(strategy="median")),
    ('std_scaler',StandardScaler())
])

full_pipeline = ColumnTransformer([
    ("num",num_pipline,float_pipeline),
    ("cat",OneHotEncoder(),object_pipeline)
])

In [67]:
import numpy as np
prep = full_pipeline.fit_transform(df)
width_len = len(prep[54].toarray())
target_len = len(df["Var_1"].unique()) + len(df["Segmentation"].unique())
label = prep[:,width_len - target_len -1:].toarray()
data = prep[:,:width_len - target_len -1].toarray()

In [68]:
from sklearn.neighbors import KNeighborsClassifier
sgd_clf = KNeighborsClassifier()
sgd_clf.fit(data,label)

KNeighborsClassifier()

In [69]:
data[54]

array([ 1.94684665, -0.45113599, -1.23799017,  0.        ,  1.        ,
        0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  1.        ])

In [70]:
sgd_clf.predict([data[5]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.]])

In [31]:
label

array([[0., 1.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [65]:
df.iloc[5]

Gender                Male
Ever_Married           Yes
Age                     56
Graduated               No
Profession          Artist
Work_Experience        0.0
Spending_Score     Average
Family_Size            2.0
Var_1                Cat_6
Segmentation             C
Name: 5, dtype: object